name: keys firebase

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v2

      - name: Cargar las claves de Firebase
        env:
          FIREBASE_CONFIG_JSON: ${{ secrets.FIREBASE_CONFIG_JSON }}
        run: |
          echo "$FIREBASE_CONFIG_JSON" > firebase-config.json

      - name: Configurar Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --project your-project-id --config firebase-config.json

