name: keys firebase

on: 
  push:
    branches:
      - main

jobs:
  keys_load:
    runs-on: ubuntu-latest
    steps:
      - name: Configurar el ambiente
        env:
          APIKEY_FIREBASE: ${{ secrets.APIKEY_FIREBASE }}
          AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
          MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
          APP_ID: ${{ secrets.APP_ID }}
        run:
          echo "Claves de Firebase cargadas correctamente"
