name: Deploy Aplication

on:
  push:
    branches:
      - master

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
      - uses: actions/setup-node@v4
        with:
          node-version: '16.6.0'
      - name: install Dependencies
        run: npm install
      - name: Deploy Firebase
        uses: w9jds/firebase-action@v4
        with:
          firebaseServiceAccount: ${{ secrets.VITE_FIREBASE_CONFIG}}
      - run: firebase deploy


        