name: Deployment Login

on:
  push:
    branches:
      - master

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: EAllaucaD/Cliente-Servidor
          path: Cliente-Servidor
      - uses: actions/setup-node@v4
        with:
          node-version: 16.6.0
      - run: npm install
        working-directory: Cliente-Servidor

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy Login with Railway
        run: railway up --service Cliente-Servidor
        working-directory: Cliente-Servidor
        env:
          RAILWAY_TOKEN: ${{ secrets.APP }}