name: Deploy Application

on:
  push:
    branches:
      - master

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
      - uses: actions/setup-node@v4
        with:
          node-version: '16.6.0'
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build

  deploy:
    needs: [login]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Railway
        if: ${{ github.event_name == 'push' }}
        uses: bervProject/railway-deploy@main
        with:
          railway_token: ${{secrets.APP}}
          service: "Cliente-Servidor"
