name: Deploy Aplication

on:
  push:
    branches:
      - master

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - name: install Dependencies
        run: npm install
      - name: Lint
        run: npm run eslint

      - uses: actions/setup-node@v4
        with:
            node-version: 'latest'
        